[package]
name = "os_str_bytes"
version = "3.1.0"
authors = ["dylni"]
edition = "2018"
exclude = [".*", "/rustfmt.toml", "/tests"]
description = """
Traits for converting between byte sequences and platform-native strings
"""
repository = "https://github.com/dylni/os_str_bytes"
readme = "README.md"
keywords = ["bytes", "osstr", "osstring", "path", "windows"]
categories = ["command-line-interface", "development-tools::ffi", "encoding", "os", "rust-patterns"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "os_str_bytes_docs_rs"]
rustdoc-args = ["--cfg", "os_str_bytes_docs_rs"]

[dev-dependencies]
getrandom = { version = "0.2", features = ["js"] }

[features]
default = ["raw_os_str"]
raw_os_str = []
