[package]
name = "os_str_bytes"
version = "2.2.0"
authors = ["dylni"]
edition = "2018"
exclude = [".*", "/rustfmt.toml", "/tests"]
description = """
Traits for converting between byte sequences and platform-native strings
"""
repository = "https://github.com/dylni/os_str_bytes"
readme = "README.md"
keywords = ["osstr", "osstring", "path", "bytes", "windows"]
categories = ["command-line-interface", "development-tools::ffi", "encoding", "os", "rust-patterns"]
license = "MIT OR Apache-2.0"

[dev-dependencies]
getrandom = "0.1"
